#!/usr/bin/env bash
# Prepare the production files of a go-tangra v4 compose deployment
# (see PRODUCTION.md, "Secrets and hardening"). Run from the repository root:
#
#   PUBLIC_HOST=tangra.example.com \
#   SMTP_HOST=smtp.example.com SMTP_PORT=587 SMTP_USERNAME=tangra@example.com \
#   SMTP_PASSWORD='...' MAIL_FROM=tangra@example.com \
#   ./scripts/prod-init.sh
#
# It creates prod/ (git-ignored), which docker-compose.production.yaml.example
# mounts instead of the development files:
#
#   prod/credentials.env   generated infrastructure + database passwords (0600)
#   prod/keys/<svc>.kek    fresh 32-byte base64 key-encryption keys (0600)
#   prod/init-db.sql       init-db.sql with one generated password per role
#   prod/configs/<svc>.yaml  configs/<svc>.yaml with the production settings
#   prod/secrets/ticket-smtp.password  SMTP password for ticket (may be empty)
#   prod/edge/             put the public edge certificate here (tls.crt/tls.key)
#
# and writes the compose-level credentials and PUBLIC_HOST into .env.
#
# Safe to re-run: credentials and KEKs are generated once and never replaced
# (they must match the database and the sealed data). prod/configs is only
# rewritten with FORCE=1 (that discards manual edits made there).
#
# Environment:
#   PUBLIC_HOST     public DNS name of the edge (required)
#   PUBLIC_PORT     public port browsers use (default 443; the origin then has no port)
#   SMTP_HOST       mail relay host (required)
#   SMTP_PORT       465 (implicit TLS) or 587 (STARTTLS) (default 587)
#   SMTP_USERNAME   relay user; empty = no SMTP authentication (IP-allow-listed relay)
#   SMTP_PASSWORD   relay password (required with SMTP_USERNAME)
#   MAIL_FROM       sender address of auth and warden mail, e.g. tangra@example.com (required)
set -euo pipefail
cd "$(dirname "$0")/.."

die() { echo "prod-init: $*" >&2; exit 1; }
: "${PUBLIC_HOST:?set PUBLIC_HOST (public DNS name of the edge)}"
: "${SMTP_HOST:?set SMTP_HOST (the real mail relay)}"
: "${MAIL_FROM:?set MAIL_FROM (sender address, e.g. tangra@example.com)}"
PUBLIC_PORT="${PUBLIC_PORT:-443}"
SMTP_PORT="${SMTP_PORT:-587}"
SMTP_USERNAME="${SMTP_USERNAME:-}"
SMTP_PASSWORD="${SMTP_PASSWORD:-}"
case "$SMTP_PORT" in
  465) SMTP_TLS=implicit ;;
  587) SMTP_TLS=starttls ;;
  *) die "SMTP_PORT must be 465 (implicit TLS) or 587 (STARTTLS): auth and warden accept only these ports with TLS" ;;
esac
[[ "$PUBLIC_HOST" =~ ^[A-Za-z0-9.-]+$ ]] || die "PUBLIC_HOST must be a bare DNS name"
[[ "$SMTP_HOST" =~ ^[A-Za-z0-9.-]+$ ]] || die "SMTP_HOST must be a bare host name"
[[ "$MAIL_FROM" =~ ^[^@[:space:]]+@([A-Za-z0-9.-]+)$ ]] || die "MAIL_FROM must be an email address"
MAIL_DOMAIN="${BASH_REMATCH[1]}"
if [ -n "$SMTP_USERNAME" ] && [ -z "$SMTP_PASSWORD" ]; then die "SMTP_PASSWORD is required with SMTP_USERNAME"; fi
if [ "$PUBLIC_PORT" = "443" ]; then ORIGIN="https://$PUBLIC_HOST"; else ORIGIN="https://$PUBLIC_HOST:$PUBLIC_PORT"; fi

SERVICES="auth gateway lcm notification warden deployer paperless inventory ipam asset ticket dns"
KEK_SERVICES="auth lcm notification deployer paperless inventory ipam asset ticket dns"

umask 077
mkdir -p prod/keys prod/configs prod/secrets prod/edge

# --- credentials (generated once) -------------------------------------------
rand() { openssl rand -hex "${1:-24}"; }
if [ ! -s prod/credentials.env ]; then
  {
    echo "# Generated by scripts/prod-init.sh on $(date -u +%FT%TZ). Keep secret; back it up."
    echo "POSTGRES_PASSWORD=$(rand)"
    echo "VALKEY_PASSWORD=$(rand)"
    echo "OPENFGA_PRESHARED_KEY=$(rand)"
    echo "RUSTFS_ACCESS_KEY=tangra$(rand 6)"
    echo "RUSTFS_SECRET_KEY=$(rand)"
    for s in $SERVICES; do echo "$(echo "$s" | tr a-z A-Z)_DB_PASSWORD=$(rand)"; done
  } > prod/credentials.env
  echo "generated prod/credentials.env"
fi
# shellcheck disable=SC1091
. prod/credentials.env

# --- key-encryption keys (generated once, never replaced) -------------------
for s in $KEK_SERVICES; do
  if [ ! -s "prod/keys/$s.kek" ]; then
    openssl rand -base64 32 > "prod/keys/$s.kek"
    echo "generated prod/keys/$s.kek"
  fi
done

# --- ticket SMTP password file (file: reference, see PRODUCTION.md) ---------
printf '%s' "$SMTP_PASSWORD" > prod/secrets/ticket-smtp.password

# --- database roles ----------------------------------------------------------
cp init-db.sql prod/init-db.sql.tmp
for s in $SERVICES; do
  v="$(echo "$s" | tr a-z A-Z)_DB_PASSWORD"
  sed -i -E "s/CREATE ROLE ${s}_app LOGIN PASSWORD 'dev'/CREATE ROLE ${s}_app LOGIN PASSWORD '${!v}'/" prod/init-db.sql.tmp
done
grep -q "PASSWORD 'dev'" prod/init-db.sql.tmp && die "init-db.sql still has a 'dev' password (unexpected role?)"
mv prod/init-db.sql.tmp prod/init-db.sql
chmod 0644 prod/init-db.sql   # read by the postgres user of the database container

# --- service configurations -------------------------------------------------
yq_str() { local v=${1//\'/\'\'}; printf "'%s'" "$v"; }   # YAML single-quoted scalar
replace_line() { # <file> <awk regex> <replacement line(s)>
  PAT="$2" REPL="$3" awk 'BEGIN{pat=ENVIRON["PAT"]; r=ENVIRON["REPL"]; n=0} $0 ~ pat {print r; n++; next} {print} END{if(n==0) exit 3}' "$1" > "$1.tmp" \
    || die "$1: no line matches /$2/"
  mv "$1.tmp" "$1"
}

if [ -d prod/configs ] && [ -n "$(ls -A prod/configs)" ] && [ "${FORCE:-0}" != "1" ]; then
  echo "prod/configs exists; keeping it (FORCE=1 regenerates it from configs/ and discards manual edits)"
else
  if [ -n "$SMTP_USERNAME" ]; then
    MAIL_AUTH=", username: $(yq_str "$SMTP_USERNAME"), password: $(yq_str "$SMTP_PASSWORD")"
  else
    MAIL_AUTH=""
  fi
  for s in $SERVICES; do
    f="prod/configs/$s.yaml"
    cp "configs/$s.yaml" "$f"
    # (discovery: warden's gRPC listener is 9843 - configs/warden.yaml
    # server.grpc_addr - while configs/{ipam,ticket,dns}.yaml name 9743.)
    v="$(echo "$s" | tr a-z A-Z)_DB_PASSWORD"
    TLSQ='sslmode=verify-full\&sslrootcert=/tls/ca.crt'
    sed -i -E \
      -e "s#postgres://${s}_app:dev@timescaledb:5432/${s}\?sslmode=disable#postgres://${s}_app:${!v}@timescaledb:5432/${s}?${TLSQ}#" \
      -e "s#postgres://postgres:dev@timescaledb:5432/${s}\?sslmode=disable#postgres://postgres:${POSTGRES_PASSWORD}@timescaledb:5432/${s}?${TLSQ}#" \
      -e "s#password: dev, allow_plaintext: true \}#password: ${VALKEY_PASSWORD}, allow_plaintext: false, ca_file: /tls/ca.crt }#" \
      -e "s#, \"https://127.0.0.1:8443\"##" \
      -e "s#https://localhost:8443#${ORIGIN}#g" \
      -e "s#use_ssl: false#use_ssl: true#" \
      -e "s#access_key: paperless#access_key: ${RUSTFS_ACCESS_KEY}#" \
      -e "s#secret_key: paperless-dev-secret#secret_key: ${RUSTFS_SECRET_KEY}#" \
      -e 's#"warden:9743"#"warden:9843"#' \
      "$f"
    case "$s" in
      ticket|dns)
        # file: secret references are refused in production mode and warden
        # references cannot be resolved unattended yet (PRODUCTION.md,
        # "Known limitations"): these two keep a non-production env label.
        replace_line "$f" '^env: dev$' 'env: dev  # production mode refuses file: secret refs - see PRODUCTION.md "Known limitations"' ;;
      *) replace_line "$f" '^env: dev$' 'env: production' ;;
    esac
    if [ "$s" != gateway ] && grep -q '^  enroll_url: https://gateway:8443/' "$f"; then
      # Workloads enroll through the public edge name (a network alias of the
      # gateway) so the first-enroll TLS dial verifies the public certificate.
      sed -i -E -e "s#^  enroll_url: https://gateway:8443/#  enroll_url: https://${PUBLIC_HOST}:8443/#" \
                -e "s#^  insecure: true\$#  insecure: false#" "$f"
    fi
  done
  f=prod/configs/auth.yaml
  replace_line "$f" '^openfga:' "openfga: { url: https://openfga:8080, preshared_key: ${OPENFGA_PRESHARED_KEY}, allow_plaintext: false }"
  replace_line "$f" '^email:' "email: { transport: smtp, host: ${SMTP_HOST}, port: ${SMTP_PORT}${MAIL_AUTH}, from: $(yq_str "$MAIL_FROM"), allow_plaintext: false }"
  replace_line "$f" '^    allow_cidrs: \["172\.31\.250\.2/32"\]$' '    allow_cidrs: []'
  f=prod/configs/warden.yaml
  replace_line "$f" '^  address: http://vault:8200$' '  address: https://vault:8200'
  replace_line "$f" '^  allow_plaintext: true$' $'  allow_plaintext: false\n  ca_file: /tls/ca.crt'
  replace_line "$f" '^mail:' "mail: { transport: smtp, host: ${SMTP_HOST}, port: ${SMTP_PORT}${MAIL_AUTH}, from: $(yq_str "$MAIL_FROM"), allow_plaintext: false }"
  replace_line prod/configs/notification.yaml '^smtp:' 'smtp: { allow_plaintext: false, dial_timeout_seconds: 30 }'
  replace_line prod/configs/lcm.yaml '^acme:' 'acme: { allow_plaintext_dns: false }'
  replace_line prod/configs/inventory.yaml '^ingest:' 'ingest: { addr: 0.0.0.0:9977, insecure: false }'
  f=prod/configs/ticket.yaml
  replace_line "$f" '^  host: mailpit$' "  host: ${SMTP_HOST}"
  replace_line "$f" '^  port: 1025$' "  port: ${SMTP_PORT}"
  replace_line "$f" '^  tls: none$' "  tls: ${SMTP_TLS}"
  if [ -n "$SMTP_USERNAME" ]; then
    replace_line "$f" '^  allow_plaintext: true$' $'  allow_plaintext: false\n  username: '"$(yq_str "$SMTP_USERNAME")"$'\n  password_ref: file:/run/secrets/smtp.password'
  else
    replace_line "$f" '^  allow_plaintext: true$' '  allow_plaintext: false'
  fi
  replace_line "$f" '^  mail_domain: example.org$' "  mail_domain: ${MAIL_DOMAIN}"
  # dns: no Docker socket in production (configuration saves report
  # restart_required; restart pdns-auth / pdns-recursor yourself).
  sed -i -E '/^docker:/,/^[a-z_]+:/ s/^  enabled: true$/  enabled: false/' prod/configs/dns.yaml
  grep -A1 '^docker:' prod/configs/dns.yaml | grep -q 'enabled: false' || die "dns.yaml: docker.enabled not switched off"
  echo "wrote prod/configs/*.yaml"
fi
chmod 0600 prod/configs/*.yaml prod/keys/*.kek prod/credentials.env prod/secrets/*

# --- leftovers check ----------------------------------------------------------
if grep -nE 'localhost:8443|sslmode=disable|:dev@|password: dev|dev-openfga-key|paperless-dev-secret|mailpit|allow_plaintext_dns: true|warden:9743' prod/configs/*.yaml; then
  die "development values left in prod/configs (see above)"
fi

# --- .env ---------------------------------------------------------------------
[ -f .env ] || cp .env.example .env
set_env() { # <key> <value>
  if grep -qE "^#?$1=" .env; then
    K="$1" V="$2" awk 'BEGIN{k=ENVIRON["K"]; v=ENVIRON["V"]; done=0} $0 ~ "^#?"k"=" && !done {print k"="v; done=1; next} {print}' .env > .env.tmp
    mv .env.tmp .env
  else
    printf '%s=%s\n' "$1" "$2" >> .env
  fi
}
for k in POSTGRES_PASSWORD VALKEY_PASSWORD OPENFGA_PRESHARED_KEY RUSTFS_ACCESS_KEY RUSTFS_SECRET_KEY; do set_env "$k" "${!k}"; done
set_env PUBLIC_HOST "$PUBLIC_HOST"
chmod 0600 .env
echo "updated .env (credentials, PUBLIC_HOST)"
echo "next: put the public certificate in prod/edge/ (tls.crt, tls.key) and follow PRODUCTION.md"
